### ISSUE TITLE
Missing {major} and {major}.{minor} tags

### ISSUE THREAD

**Issue by moikot** [alpine-docker/helm#30]
It would we really great to have {major} and {major}.{minor} tags in addition to {major}.{minor}.{patch} so that one can pull using somthing like:

```bash
docker pull alpine/helm:3
```

**Comment by ozbillwang** [comment]
I am not going to do that, because if one day, there is version 4.x, I have to make sure both v4 and v3 latest. 

Second, the main purpose for this repo is to simplify the cicd pipeline. For best practices, you shouldn't use any latests tag or v3 version tag without minor and patch version. The reason is, you need make sure the build successfully without depend on the  same tag, but in fact the real version is changed.

**Comment by felipecrs** [comment]
@ozbillwang 
> I have to make sure both v4 and v3 latest

We can use the `semver` CLI, and it would be extremely simple and should work for every upcoming release.

Would you welcome a PR?

**Comment by mamoit** [comment]
Sorry for the necromancy.
I understand not wanting to keep a `3` tag with the bleeding edge.
But a tag for each minor version would be a very welcome improvement.

For example, right now there helm `3.7.0` is the latest version, and next week there should be a patch release.
It would be nice if we could use `3.7` in a CI declaration and not have to update it on every single patch.
