### ISSUE TITLE
Image builds frozen?

### ISSUE THREAD

**Issue by jnoordsij** [alpine-docker/helm#49]
Yesterday [Helm 3.10.3](https://github.com/helm/helm/releases/tag/v3.10.3) was released. Usually the images are built weekly on thursdays around this time, but looking at [the build logs](https://app.travis-ci.com/github/alpine-docker/helm/builds) it seems like there hasn't been any builds for 4 weeks.

Is there a change in the build schedule, or is it actually frozen?

**Comment by ozbillwang** [comment]
let me check.

**Comment by ozbillwang** [comment]
that's bad, no credit to run the build in travis ci

![image](https://user-images.githubusercontent.com/8954908/208325127-47dda2bb-27b7-43ae-acec-3a32a2c7fc07.png)

===
Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the [Plan page](https://app.travis-ci.com/organizations/alpine-docker/plan) to replenish your credit balance or alter your [Consume paid credits for OSS setting](https://app.travis-ci.com/organizations/alpine-docker/plan?anchor=oss-consumption).
===

need migrate this project to other cicd pipeline, maybe think about Github Action or CircleCI.

**Comment by jduepmeier** [comment]
@ozbillwang the error in travis is now:

```
user has not confirmed their email address
```
https://app.travis-ci.com/github/alpine-docker/helm/requests

**Comment by ozbillwang** [comment]
same reason, no free pipeline time for me. 

The Travis CI is suck, after migrated from *.org to *.com 

I have to migrate most projects in this group to Circle CI , but I need free time to work on it, have to wait.

**Comment by jonesbusy** [comment]
Same "issue" here. Waiting for newer tags on dockerhub.

Thanks

**Comment by hilariocoelho** [comment]
Helm 3.11.1 includes a security patch where users are strongly recommended to update. It would be nice to have a new alpine/helm image based on helm:3.11.1

**Comment by ozbillwang** [comment]
> can I submit a circle-ci config?

of couse. This project has consistant way to build the images. Please take reference of this templae when you submit the PR

strategy

**Comment by ozbillwang** [comment]
The pipeline has been switched from Travis CI to Circle CI,  latest tag `3.11.1` is ready now

Plus, tag `latest` supports multi-arch images as well with [crane copy](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane_copy.md)

https://github.com/alpine-docker/helm/blob/master/build.sh#L53

**Comment by ozbillwang** [comment]
Please help to run test for the new image, especially for other platforms. 

```
docker run -ti --rm alpine/helm version
```
